version: 2
updates:
   - package-ecosystem: "npm"
     directory: "/"
     schedule:
        interval: "weekly"
        day: "thursday"
        time: "18:10"
        timezone: "America/Costa_Rica"
     target-branch: "main"
     labels:
        - "dependencies"
